return {
	rosewater = "{{colors.primary.default.hex}}",
	flamingo = "{{colors.secondary.default.hex}}",
	pink = "{{colors.tertiary.default.hex}}",
	mauve = "{{colors.primary.default.hex}}",
	red = "{{colors.error.default.hex}}",
	maroon = "{{colors.error.default.hex}}",
	peach = "{{colors.secondary_container.default.hex}}",
	yellow = "{{colors.tertiary_container.default.hex}}",
	green = "{{colors.primary_container.default.hex}}",
	teal = "{{colors.secondary.default.hex}}",
	sky = "{{colors.tertiary.default.hex}}",
	sapphire = "{{colors.primary.default.hex}}",
	blue = "{{colors.primary.default.hex}}",
	lavender = "{{colors.tertiary.default.hex}}",

	text = "{{colors.on_background.default.hex}}",
	subtext1 = "{{colors.on_surface_variant.default.hex}}",
	subtext0 = "{{colors.on_surface_variant.default.hex}}",
	overlay2 = "{{colors.outline.default.hex}}",
	overlay1 = "{{colors.outline_variant.default.hex}}",
	overlay0 = "{{colors.surface_variant.default.hex}}",
	surface2 = "{{colors.surface_container_highest.default.hex}}",
	surface1 = "{{colors.surface_container_high.default.hex}}",
	surface0 = "{{colors.surface_container.default.hex}}",

	base = "{{colors.background.default.hex}}",
	mantle = "{{colors.surface_dim.default.hex}}",
	crust = "{{colors.surface.default.hex}}",
}
